### ISSUE TITLE
Creating a Gallery Generates an Empty Searchable Post 

### ISSUE THREAD

**Issue by kmkroma** [enviragallery/envira-gallery-lite#16]
Helpscout Ticket: https://secure.helpscout.net/conversation/994022114/64380/

## Debug Information (From System Info Tab)
<details>
<summary>System Info Data</summary>

</details>

## Expected Behavior

New Galleries should not generate a searchable post.
## Current Behavior

Publishing a gallery also publishes a searchable post.
## Possible Solution

add_filter('envira_gallery_post_type_args', 'prefix_hide_envira_from_search', 10, 1 );
function prefix_hide_envira_from_search( $args ) {
    $args['exclude_from_search'] = true;
    return $args;
}

## Steps to Reproduce (for bugs)

1.  Create a new gallery using Envira Lite
2. Publish your Gallery
3. Search your site for the title of the gallery
4. Take note of the post visible in the search results.

## Your Environment

Browser name and version:
Operating System and version (desktop or mobile):

## Screenshots (if appropriate)

https://share.getcloudapp.com/Z4uzALbw

**Comment by kmkroma** [comment]
Customer is asking for an update on this: https://secure.helpscout.net/conversation/994022114/0/?folderId=3193753

**Comment by dimensionmedia** [comment]
This also released. Closing.
