### ISSUE TITLE
Lite image dimensions not rendering properly

### ISSUE THREAD

**Issue by greatknave** [enviragallery/envira-gallery-lite#17]
Helpscout Ticket: https://secure.helpscout.net/conversation/1011594565/65152?folderId=3302565

## Expected Behavior

When you define image dimensions in a nonautomatic-columns gallery, cropping enabled, images should display in the defined sizes.

## Current Behavior

Customer has three-column gallery's image dimensions set to 300x300 (or any dimensions), images cropped, but images display in assorted sizes. (See screenshots below.)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WP-ADMIN Access And Url

http://amiel-bakehila.org/wp-admin
User: envira
Pass: xO^GE^(!CwaEHsfq7BLavK)a

## Context

The gallery in question is in a draft post, in case you go looking for it. I'm able to reproduce the error in the same site — Jetpack and other plugins' lazy-loading, etc., have been disabled.

## Your Environment

Browser name and version:
Operating System and version (desktop or mobile):

## Screenshots (if appropriate)

The display of a three-column gallery, cropping enabled, with images defined as 300x300:

![image](https://user-images.githubusercontent.com/56563598/69358736-553c7380-0c55-11ea-8c79-0e7ea7d7e5b2.png)

**Comment by dimensionmedia** [comment]
@greatknave created test page: http://amiel-bakehila.org/wp-admin/post.php?post=4466&action=edit

**Comment by dimensionmedia** [comment]
Deactivating JetPack made this work. I checked the image src before I did and the images were going to a wp.com CDN.

Sadly @greatknave when i reactivated Jetpack it needs to be reconnected. You can login via the admin and see for yourself:

http://amiel-bakehila.org/wp-admin/admin.php?page=jetpack#/

Screenshot attached once I turned off Jetpack. I would say that having Jetpack on probably isn't the problem, it's probably the CDN feature. Envira doesn't support CDN... you know the rest of the story. Therefore closing ticket.

![Screen Shot 2020-05-20 at 8 48 19 AM](https://user-images.githubusercontent.com/721134/82447991-127a1d80-9a77-11ea-8876-d6f8cf8b5710.png)
