### ISSUE TITLE
Gifs are being outputted as cropped versions and are not playing in gallery view.

### ISSUE THREAD

**Issue by kmkroma** [enviragallery/envira-gallery-lite#18]
https://wordpress.org/support/topic/gif-not-playing/

Make a gallery in lite using a gif file, make sure you're setting the image to show full size and are not using cropping.

Notice that the gif doesn't play in your gallery. Lightbox is fine.

**Comment by dimensionmedia** [comment]
![Screen Shot 2020-05-20 at 9 19 53 AM](https://user-images.githubusercontent.com/721134/82450745-14de7680-9a7b-11ea-81a2-3853a8fc44cb.png)

**Comment by dimensionmedia** [comment]
Released w/ 1.7.8.8
