### ISSUE TITLE
Deprecated: media_buttons_context in editor.php

### ISSUE THREAD

**Issue by greatknave** [enviragallery/envira-gallery-lite#31]
From a .org ticket:

_I have a persistent error in my log for a usage of media_buttons_context which has been deprecated since 3.5! Because of another error I decided to try and locate the user and found it in includes\admin\editor.php on line 59:_

_add_filter( ‘media_buttons_context’, array( $this, ‘media_button’ ) );_

_As soon as I switch off Envira Gallery Lite this error disappears. According to the error, you should use media_buttons in stead._

**Comment by dimensionmedia** [comment]
Is it literally

```
add_filter( 'media_buttons', array( $this, 'media_button' ) );
```
