### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by NickB949** [enviragallery/envira-gallery-lite#34]
Please fix a broken link inside the LITE plugin: 

Under the "Getting Started Tab"

<img width="960" alt="2020-06-02_15-11-55" src="https://user-images.githubusercontent.com/56736940/83560096-a7ebc780-a4e3-11ea-9b3f-aec20cd1e0f0.png">

Please add the following link/UTM code:

https://enviragallery.com/how-to-optimize-image-galleries-for-mobile-using-envira-gallery/?utm_source=liteplugin&utm_medium=gettingstartedtab&utm_campaign=customizewordpressgalleriesformobile

**Comment by dimensionmedia** [comment]
out with 1.7.9.0
