### ISSUE TITLE
Allow updating with WP-CLI

### ISSUE THREAD

**Issue by sdenike** [enviragallery/envira-gallery-lite#35]
This is more for the paid version, but I would love to see the ability for the plugin and addons to be updated from WP-CLI.

I assume the update function differs from the one that WP Core expects as mentioned here https://github.com/wp-cli/wp-cli/issues/1662

**Comment by chrisakelley** [comment]
@sdenike I'm transferring this issue to Pro repo which is private as Lite can already be updated via CLI
