### ISSUE TITLE
Lightbox disabled, no image links (use case)

### ISSUE THREAD

**Issue by akyusa01** [enviragallery/envira-gallery-lite#4]
User wants to use 3rd party lightbox.  When you disable Envira Lite lightbox (on the Lightbox tab), no image links are viewed so the 3rd party lightbox doesn't work

HS Ticket: https://secure.helpscout.net/conversation/559339041/27345/

1.  Create a Lite gallery, make sure the image links are there on the images
2.  Make sure the lightbox is disabled
3.  View the gallery, can't see the links.

I believe this is more part in line of what we discussed with the premium version, but there we added a button to enable the links or enable the lightbox.  Lite users want differently - but not sure if we should just say well that's an up-sell thing?  

Documenting here to let you all decide.

**Comment by akyusa01** [comment]
UPDATE: gave them custom js to do this as a work around:

`jQuery(document).ready(function() {
  jQuery('img.envira-gallery-image').each(function ()
  {
     var currentImage = jQuery(this); 
     currentImage.wrap("<a href='" + currentImage.attr("src") + "' </a>");
  });
});`

**Comment by chrisakelley** [comment]
Note: This will change with Fancybox3 Lite release.

**Comment by akyusa01** [comment]
Leaving open

**Comment by dimensionmedia** [comment]
@chrisakelley for an easy "feature" for a lite push can we add the "enable links" for Lite similar to what we do for Pro?

**Comment by dimensionmedia** [comment]
Finally nailed in today's release of 1.8.0.0
