### ISSUE TITLE
New changes to the Get Started Tab 

### ISSUE THREAD

**Issue by NickB949** [enviragallery/envira-gallery-lite#46]
Please make the following changes to the Get Started Tab inside Envira Gallery LITE:

Let’s replace some of the old articles with new articles that correspond with the top-selling addons based on revenue inside GA.

<img width="960" alt="2020-09-18_11-01-56" src="https://user-images.githubusercontent.com/56736940/93617776-66a0fa00-f9a4-11ea-9801-37cbf9c3c1ad.png">

Replace how to create your first gallery with: 

How to get started with Envira Gallery 
Link: https://enviragallery.com/how-to-use-envira-gallery/?utm_source=liteplugin&utm_medium=gettingstartedtab&utm_campaign=howtouseenviragallery

Replace How to create and synchronize your Adobe Lightroom Collections with:

How to optimize image galleries for mobile using Envira Gallery
Link: https://enviragallery.com/how-to-optimize-image-galleries-for-mobile-using-envira-gallery/?utm_source=liteplugin&utm_medium=gettingstartedtab&utm_campaign=howtooptimizeimagegalleriesformobile

Replace How to turn your photos into products and make money from your photography with:
 
How to sell your photos in WordPress
Link: 
https://enviragallery.com/how-to-sell-your-photos-in-wordpress/?utm_source=liteplugin&utm_medium=gettingstartedtab&utm_campaign=howtosellyourphotosinwordpress

Replace How to appear higher in Google search results... with:

How to enhance gallery layouts with customizable gallery themes
Link: 
https://enviragallery.com/how-to-enhance-gallery-layouts-with-customizable-gallery-themes/?utm_source=liteplugin&utm_medium=gettingstartedtab&utm_campaign=howtoenhancegallerylayouts

Let's keep the same article where it is: How to protect your galleries and images from online theft

Let's remove this section: 
<img width="960" alt="2020-09-18_11-38-53" src="https://user-images.githubusercontent.com/56736940/93618288-0e1e2c80-f9a5-11ea-8a95-f5cda746db39.png">

Let's remove this article from this section:
<img width="960" alt="2020-09-18_11-39-11" src="https://user-images.githubusercontent.com/56736940/93618315-16766780-f9a5-11ea-807d-8fba79395acb.png">

@nathansingh1 Anything you want to add or that I've missed?

**Comment by NickB949** [comment]
All of these changes are good to go! 

Please double-check that the styling is properly aligned at the very bottom of the tab (see screenshot below). 

<img width="960" alt="2020-09-28_13-31-16" src="https://user-images.githubusercontent.com/56736940/94466293-3b31c280-018f-11eb-9e93-5913916d30ad.png">

**Comment by dimensionmedia** [comment]
![Screen Shot 2020-09-28 at 1 55 45 PM](https://user-images.githubusercontent.com/721134/94468376-505c2080-0192-11eb-948a-2c1fe5b60fb1.png)

**Comment by NickB949** [comment]
Works now. Good to go. Thanks!
