### ISSUE TITLE
New changes to the What's New Tab

### ISSUE THREAD

**Issue by NickB949** [enviragallery/envira-gallery-lite#47]
For the What’s New Tab

Replace the Social Addon with the Elementor Addon 
Replace the Videos Addon with the Audio Addon

For both of these put a “New” tab beside them. 

<img width="960" alt="2020-09-18_10-55-36" src="https://user-images.githubusercontent.com/56736940/93619413-86392200-f9a6-11ea-97c5-abcb50d78c84.png">

I'm open to suggestions on whether we should keep the Gutenberg announcement there or replace it with something else...

**Comment by dimensionmedia** [comment]
![Screen Shot 2020-09-28 at 1 12 45 PM](https://user-images.githubusercontent.com/721134/94464309-4fc08b80-018c-11eb-81aa-223c0285e21f.png)

**Comment by NickB949** [comment]
Good to go. Thanks!
