### ISSUE TITLE
Responsive Gallery With Lightbox Breaks Gallery Edit Screen Image Editing

### ISSUE THREAD

**Issue by bhadaway** [enviragallery/envira-gallery-lite#5]
Breaks the Lightbox on the gallery edit screen so that clicking the white/blue pencil icon to edit an individual image doesn't work.

## Expected Behavior
When on the gallery editing screen and you click on the white/blue pencil edit icon for an individual image, it should open the edit options in a Lightbox.

## Current Behavior
When you click on the edit icon, nothing happens.

## Possible Solution
Contact plugin author and have them update their code so that it's not activated admin side:

`if ( ! is_admin() )`

https://wordpress.org/plugins/responsive-gallery-with-lightbox/

## Screenshots
https://cl.ly/0e113E152s0K

**Comment by akyusa01** [comment]
Closing this, with the latest version of both plugins, this is no longer an issue.
