### ISSUE TITLE
Lightbox Nav/Close Not Displaying in WP 5.6

### ISSUE THREAD

**Issue by bmilligan15** [enviragallery/envira-gallery-lite#59]
With the recent WordPress 5.6 update, it appears the Lite lightbox navigation/close functionality is no longer working. Reports are starting to come in, and I'm able to duplicate locally. On my local, I'm running WP 5.6 with Twenty Twenty, and only Envira Lite active.

lite.enviragallery.com is currently on 5.6 as well, and confirmed here: http://lite.enviragallery.com/2020/12/09/5-6-gallery/

Please see the gallery here for reference: http://ucdtest.ucandancestudio.com/wordpress/hall-rental-views/

**Comment by bmilligan15** [comment]
Another report: https://secure.helpscout.net/conversation/1363379641/83586?folderId=1769539

**Comment by bmilligan15** [comment]
https://secure.helpscout.net/conversation/1363457538/83590?folderId=4156775
https://secure.helpscout.net/conversation/1363485901/83591?folderId=4156775
https://secure.helpscout.net/conversation/1363528405/83593?folderId=4156775

These have come in after-hours. One is a user from .org who posted earlier today.

**Comment by bmilligan15** [comment]
https://secure.helpscout.net/conversation/1364076665/83622?folderId=1769539

**Comment by chrisakelley** [comment]
released in 1.8.3.2
