### ISSUE TITLE
Update the Upgrade Wording

### ISSUE THREAD

**Issue by nathansingh1** [enviragallery/envira-gallery-lite#8]
-Update the current wording here: https://cl.ly/615924ca84b3

to: 

"Want to make your gallery workflow and presentation even better?

By upgrading to Envira Pro, you can get access to numerous other features, including: Albums, Gallery Themes/Layouts, Image Proofing, eCommerce, dedicated customer support and so much more!"

*We should link the above features with their demo page links  
Albums <https://enviragallery.com/demo/albums-demo/>
Gallery Themes/Layouts <https://enviragallery.com/demo/envira-gallery-theme-demo/>
Video Galleries <https://enviragallery.com/demo/video-gallery-demo/>
Social Sharing <https://enviragallery.com/demo/social-sharing-demo/>
Image Proofing <https://enviragallery.com/demo/proofing-gallery-demo/>
Ecommerce <https://enviragallery.com/addons/woocommerce-addon/>

-Update the current wording here: https://cl.ly/a4cd3173f257 to remove Google+ and add Instagram.

-Update the current wording here: https://cl.ly/ce3bf04cc783 to add the other options DailyMotion IGTV etc

-Update mousehweel to "mouse wheel": https://cl.ly/17d82212d6bd 

-We should rewrite some of these and put screen shots in each one of these:
https://cl.ly/b31f849b9407

**Comment by akyusa01** [comment]
Leaving open.

**Comment by dimensionmedia** [comment]
This might be a bit outdated so i'm assuming @nathansingh1 will review all marketing text but I did update the bits he pointed out that weren't already updated by other tickets.

It's up on lite.enviragallery.com.

![Screenshot 2019-06-03 10 19 32](https://user-images.githubusercontent.com/721134/58809053-2ff57380-85e9-11e9-832d-e384d022c078.png)

**Comment by dimensionmedia** [comment]
To the best I can tell, all of this is already live or was replaced by later tickets with @nathansingh1 advising me better copy/wording for some screens.

I'm closing this ticket. cc: @chrisakelley
