### ISSUE TITLE
Envira Lite showing HTML Tags in Title

### ISSUE THREAD

**Issue by bmilligan15** [enviragallery/envira-gallery-lite#9]
I've got a client who is having an issue with Envira Lite showing the HTML tags within the image title field. I was able to confirm this locally as well. This only seems to be occurring on Envira Lite, and not our paid version.

https://secure.helpscout.net/conversation/852886889/49581?folderId=2211390

FTP
===
Username: temp-envira@bigso.hemsida.eu
Pass: Z6oy05@gU0OXy03JM)I3jU7(
FTP-server: ftp.bigso.com
FTP & explicit FTPS-port: 21

WP Admin
========
http://bigso.hemsida.eu/wp-admin/
temp-envira
Z6oy05@gU0OXy03JM)I3jU7(

Expected Behavior: HTML tags should not be showing in either gallery or lightbox view.

Current Behavior: HTML tags seem to be showing in both gallery and lightbox view.

![Screen Shot 2019-05-14 at 12 57 26 PM](https://user-images.githubusercontent.com/17555874/57717049-578b9880-7648-11e9-94ac-228f0dbda4b3.png)

![Screen Shot 2019-05-14 at 12 58 24 PM](https://user-images.githubusercontent.com/17555874/57717058-5bb7b600-7648-11e9-853f-f289d8d7b017.png)

**Comment by bmilligan15** [comment]
Doc'ing only, client is impatient. https://secure.helpscout.net/conversation/852886889/49581?folderId=2211390

**Comment by bmilligan15** [comment]
Another report: https://secure.helpscout.net/conversation/860824980/50066?folderId=2211390

**Comment by dimensionmedia** [comment]
https://github.com/enviragallery/envira-gallery-lite/commit/7b109506e01802d7c5c09679c0fe037084d4b8cb

**Comment by dimensionmedia** [comment]
I've pushed changes here:

http://lite.enviragallery.com/envira-lite-showing-html-tags-in-title-9/

@bmilligan15 @chrisakelley

**Comment by dimensionmedia** [comment]
@chrisakelley @bmilligan15 I confirmed this fix should already be in Lite live. I'm closing but @kmkroma @bmilligan15 please note this and reopen if we see this being reported again.
